/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package di.dam.tareaev1_25._apartado1.vista;

import di.dam.tareaev1_25._apartado1.controlador.ReservaControlador;
import di.dam.tareaev1_25._apartado1.modelo.Reserva;
import di.dam.tareaev1_25._apartado1.modelo.ReservaTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author jose
 */
public class ReservaJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservaJFrame.class.getName());    
    private ReservaControlador rc;
    private ReservaTableModel rtm;

    /**
     * Creates new form ReservaJFrame
     */
    public ReservaJFrame(ReservaControlador rc) {
        initComponents();
        
        this.rc = rc;
        rtm = new ReservaTableModel(rc.getReservas());
        
        poblarTabla(rtm);
        
    }
    
    /** 
     * Método que maneja la tabla
     */
    private void poblarTabla(ReservaTableModel rtm) {           
        this.jTableReservas.setModel(rtm);
        
        TableRowSorter<ReservaTableModel> trs = new TableRowSorter<>(rtm);
        
        this.jTableReservas.setRowSorter(trs);
    }

    /**
     * Método que añade una reserva desde fuera del JFrame
     */
    public void altaReserva(Reserva reserva){
        rc.addReserva(reserva);
        rtm = new ReservaTableModel(rc.getReservas());        
        poblarTabla(rtm);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReservas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFiltroNombre = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPista = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonPagado = new javax.swing.JRadioButton();
        jRadioButtonPendiente = new javax.swing.JRadioButton();
        jRadioButtonCancelado = new javax.swing.JRadioButton();
        jButtonEditarReserva = new javax.swing.JButton();
        jButtonBorrarReserva = new javax.swing.JButton();
        jButtonAnadirReserva = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea EV1 DAM/DI");
        setLocationByPlatform(true);

        jTableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReservas);

        jLabel1.setText("Filtrar reservas:");

        jButtonBuscar.setText("Buscar");

        jLabel2.setText("Cliente:");

        jLabel3.setText("Pista");

        jComboBoxPista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pádel", "Frontón", "Fútbol sala", "Baloncesto" }));

        jLabel4.setText("Estado:");

        jRadioButtonPagado.setText("Pagado");

        jRadioButtonPendiente.setText("Pendiente");

        jRadioButtonCancelado.setText("Cancelado");

        jButtonEditarReserva.setText("Editar");

        jButtonBorrarReserva.setText("Borrar");

        jButtonAnadirReserva.setText("Añadir");
        jButtonAnadirReserva.addActionListener(this::jButtonAnadirReservaActionPerformed);

        jMenu1.setText("Fichero");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(this::jMenuItemSalirActionPerformed);
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem1.setText("Nueva Reserva");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Editar Reserva");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Borrar Reserva");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ayuda");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Acerca de");
        jRadioButtonMenuItem1.addActionListener(this::jRadioButtonMenuItem1ActionPerformed);
        jMenu5.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonPagado)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPendiente)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCancelado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFiltroNombre)
                            .addComponent(jComboBoxPista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonAnadirReserva)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditarReserva)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBorrarReserva)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarReserva)
                    .addComponent(jButtonBorrarReserva)
                    .addComponent(jButtonAnadirReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonPagado)
                    .addComponent(jButtonBuscar)
                    .addComponent(jRadioButtonPendiente)
                    .addComponent(jRadioButtonCancelado))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Tarea EV1 de DAM/DI.", "Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jButtonAnadirReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirReservaActionPerformed
       ReservaJDialog rjd = new ReservaJDialog(this, true);
       rjd.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirReservaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirReserva;
    private javax.swing.JButton jButtonBorrarReserva;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditarReserva;
    private javax.swing.JComboBox<String> jComboBoxPista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JRadioButton jRadioButtonCancelado;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButton jRadioButtonPagado;
    private javax.swing.JRadioButton jRadioButtonPendiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableReservas;
    private javax.swing.JTextField jTextFieldFiltroNombre;
    // End of variables declaration//GEN-END:variables
}
