/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package di.dam.ejemplo6componente;

import java.io.Serializable;

/**
 *
 * @author jose
 */
public class JPanelComponente extends javax.swing.JPanel  implements Serializable{

    private String lblTexto;
    /**
     * Creates new form JPanelComponente
     */
    public JPanelComponente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelComponente = new javax.swing.JLabel();

        jLabelComponente.setText("Esto es un componente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelComponente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelComponente))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getLblTexto() {
        lblTexto = jLabelComponente.getText();
        return lblTexto;
    }

    public void setLblTexto(String lblTexto) {
        this.lblTexto = lblTexto;
        this.jLabelComponente.setText(lblTexto);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelComponente;
    // End of variables declaration//GEN-END:variables
}
