/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package di.dam.ejemploclase5.vista;

import di.dam.ejemploclase5.controlador.AlumnoControlador;
import di.dam.ejemploclase5.modelo.Alumno;
import di.dam.ejemploclase5.modelo.AlumnoTableModel;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author joseDefaultTableModel
 */
public class JFramePrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePrincipal.class.getName());
    private AlumnoControlador ac;
    private AlumnoTableModel atm;
   
    
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal(AlumnoControlador ac) {
        initComponents();
        
        this.ac = ac;
        try {
            atm = new AlumnoTableModel(ac.getListaAlumnos());
        } catch (SQLException ex) {
            System.getLogger(JFramePrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(
                    this,
                    "Error:\n" + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
        
        poblarTabla(atm);
        
    }

    /**
     * Método que añade un alumno
     */
    public void altaAlumno(Alumno alumno){
        try {
            ac.altaAlumno(alumno);
            atm = new AlumnoTableModel(ac.getListaAlumnos());
            poblarTabla(atm);
        } catch (SQLException ex) {
            System.getLogger(JFramePrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(
                this,
                "Error:\n" + ex.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } catch (IllegalArgumentException ex) {
            System.getLogger(JFramePrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(
                this,
                "Error:\n" + ex.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    /**
     * Método que modifica un alumno
     */
    public void modificacionAlumno(Alumno alumno) {
        try {
            ac.actualizarAlumno(alumno);
            atm = new AlumnoTableModel(ac.getListaAlumnos());
            poblarTabla(atm);
        } catch (SQLException ex) {
            System.getLogger(JFramePrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                JOptionPane.showMessageDialog(
                    this,
                    "Error:\n" + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
    /** 
     * Método que maneja la tabla
     */
    private void poblarTabla(AlumnoTableModel atm) {           
        this.jTableAlumnos.setModel(atm);
        
        // Añadimos la ordenación de elementos
        TableRowSorter<AlumnoTableModel> trs = new TableRowSorter<>(atm);
        
        this.jTableAlumnos.setRowSorter(trs);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemFiltrar = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemDocumentacion = new javax.swing.JMenuItem();
        jMenuItemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumnos");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableAlumnos);

        jLabel1.setText("Filtro:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jMenuSalir.setText("Archivo");

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar.add(jMenuSalir);

        jMenuAlumnos.setText("Alumnos");

        jMenuItemNuevo.setText("Nuevo alumno");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemNuevo);

        jMenuItemFiltrar.setText("Filtrar");
        jMenuAlumnos.add(jMenuItemFiltrar);

        jMenuBar.add(jMenuAlumnos);

        jMenuAyuda.setText("Ayuda");

        jMenuItemDocumentacion.setText("Documentación");
        jMenuAyuda.add(jMenuItemDocumentacion);

        jMenuItemAcerca.setText("Acerca de...");
        jMenuItemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcerca);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBorrar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonEditar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Ejemplo de DAM/DI.","Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAcercaActionPerformed

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        JDialogAlta jda = new JDialogAlta(this, true);
        jda.setVisible(true);
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String consulta = this.jTextFieldBuscar.getText();
        if (!consulta.isEmpty() && !consulta.isBlank()){
            this.jTableAlumnos.setModel(atm);
            // Añadimos la ordenación de elementos
            TableRowSorter<AlumnoTableModel> trs = new TableRowSorter<>(atm);          
            trs.setRowFilter(RowFilter.regexFilter(consulta));
            this.jTableAlumnos.setRowSorter(trs);
        } else {
            JOptionPane.showMessageDialog(this, "Error de filtrado", "El filtro se encuentra vacío", JOptionPane.WARNING_MESSAGE);
            this.poblarTabla(atm);
        }       
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int seleccionado = this.jTableAlumnos.getSelectedRow();
        int elementoABorrar = (int)this.jTableAlumnos.getValueAt(seleccionado, -1);
        //JOptionPane.showMessageDialog(this, "Vamos a borrar el elemento: "+elementoABorrar, "El elemento seleccionado es: "+seleccionado, JOptionPane.WARNING_MESSAGE);
        
        String elemento = this.jTableAlumnos.getValueAt(seleccionado, 0) + " " + this.jTableAlumnos.getValueAt(seleccionado, 1);
        int confirmar = JOptionPane.showConfirmDialog(this, "Vas a eliminar el elemento: " + elemento, "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION){
            try {
                //Borrar elemento
                this.ac.borrarUsuario(elementoABorrar);
                atm = new AlumnoTableModel(ac.getListaAlumnos());
                this.poblarTabla(atm);
            } catch (SQLException ex) {
                System.getLogger(JFramePrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        } else {
            JOptionPane.showConfirmDialog(this, "No vas a borrar nada", "Confirmar", JOptionPane.CANCEL_OPTION);
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int seleccionado = this.jTableAlumnos.getSelectedRow();
        int id = (int)this.jTableAlumnos.getValueAt(seleccionado, -1);
        String nombre = (String)this.jTableAlumnos.getValueAt(seleccionado, 0);
        String apellidos = (String)this.jTableAlumnos.getValueAt(seleccionado, 1);
        Date alta = (Date)this.jTableAlumnos.getValueAt(seleccionado, -2);
        String ciclo = (String)this.jTableAlumnos.getValueAt(seleccionado, 3);
        String curso = (String)this.jTableAlumnos.getValueAt(seleccionado, 4);
        Alumno alumno = new Alumno(id, nombre, apellidos, alta, ciclo, curso);
        
        JDialogAlta jda = new JDialogAlta(this, true, alumno);
        jda.setVisible(true);
       
    }//GEN-LAST:event_jButtonEditarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemAcerca;
    private javax.swing.JMenuItem jMenuItemDocumentacion;
    private javax.swing.JMenuItem jMenuItemFiltrar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAlumnos;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables

}
