/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package di.dam.tareaev1_25._apartado2;

import java.io.Serializable;

/**
 *
 * @author jose
 */
public class TomatesJPanel extends javax.swing.JPanel implements Serializable{
    
    /**
     * Atributos que debéis publicar como propiedades:
     */
    
    private int periodos;    
    private int minutosPeriodo;
    private int minutosDescansoCorto;
    private int minutosDescansoLargo;

    private int periodoActual; // Este no se debe publicar, se calculará en tiempo real cada vez que se inicie un pomodoro o un descanso sumará 1.
    
    /**
     * Creates new form TomatesJPanel
     */
    public TomatesJPanel() {
        initComponents();
        
        // Iniciamos en el perido 0.
        periodoActual = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFijo = new javax.swing.JLabel();
        jLabelPeriodo = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();

        jLabelFijo.setText("Periodo:");

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(this::jButtonIniciarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFijo)
                    .addComponent(jLabelPeriodo)
                    .addComponent(jButtonIniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        periodoActual++;
        TomatesJDialog tjd = new TomatesJDialog(minutosPeriodo);
        periodoActual++;
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void actualizaEtiqueta(){
        //
        // AQUÍ VUESTRO CÓDIGO
        //
    }

    /**
     * Métodos que van a mostrar las propiedades en el editor
     */
    public int getPeriodos() {
        return periodos;
    }

    public void setPeriodos(int periodos) {
        this.periodos = periodos;
    }

    public int getMinutosPeriodo() {
        return minutosPeriodo;
    }

    public void setMinutosPeriodo(int minutosPeriodo) {
        this.minutosPeriodo = minutosPeriodo;
    }

    public int getMinutosDescansoCorto() {
        return minutosDescansoCorto;
    }

    public void setMinutosDescansoCorto(int minutosDescansoCorto) {
        this.minutosDescansoCorto = minutosDescansoCorto;
    }

    public int getMinutosDescansoLargo() {
        return minutosDescansoLargo;
    }

    public void setMinutosDescansoLargo(int minutosDescansoLargo) {
        this.minutosDescansoLargo = minutosDescansoLargo;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabelFijo;
    private javax.swing.JLabel jLabelPeriodo;
    // End of variables declaration//GEN-END:variables
}
