/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package di.dam.tareaev1_25._apartado2;

import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author jose
 */
public class TomatesJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TomatesJDialog.class.getName());
    private int minutosPeriodo;
    private Timer timer;
    private long inicio;

    /**
     * Creates new form TomatesJDialog
     * @param minutos
     */
    public TomatesJDialog(int minutosPeriodo) {
        super(new javax.swing.JFrame(), true);
        initComponents();
        this.minutosPeriodo = minutosPeriodo;
        this.setVisible(true);
        timer = new Timer(100, (ActionEvent e) -> actualizarTiempo());
        timer.start();
        //
        // AQUÍ VUESTRO CÓDIGO
        //
        this.dispose();
    }
    
    private void actualizarTiempo() {
        //
        // LA CUENTA DEBE SER AL REVES
        //
        long ahora = System.currentTimeMillis();
        long tiempo = ahora - inicio;

        long minutos = (tiempo / 60000);
        long segundos = (tiempo % 60000) / 1000;
        long milis   = tiempo % 1000;

        this.jLabelCuenta.setText(String.format("%02d:%02d:%03d", minutos, segundos, milis));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFijo = new javax.swing.JLabel();
        jLabelCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tiempo restante");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);

        jLabelFijo.setText("Tiempo de concentración restante:");

        jLabelCuenta.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabelCuenta.setText("HH:MM:SS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFijo)
                    .addComponent(jLabelCuenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCuenta)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelFijo;
    // End of variables declaration//GEN-END:variables
}
