/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package di.dam.ejemploclase6proyecto;

import java.io.Serializable;

/**
 *
 * @author jose
 */
public class JFrameVentana extends javax.swing.JFrame implements Serializable{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameVentana.class.getName());

    /**
     * Creates new form JFrameVentana
     */
    public JFrameVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComponenteError = new di.dam.ejemplo6componente.JPanelComponente();
        jTextFieldDivisor = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jTextFieldDividendo = new javax.swing.JTextField();
        jLabelResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelImagenTransparente2 = new di.dam.ejemploclase6componente3.JPanelImagenTransparente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComponenteError.setLblTexto("");

        jButtonModificar.setText("Dividir");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabelResultado.setText("Resultado: ");

        jLabel1.setText("Calculadora que puede generar excepciones:");

        jPanelImagenTransparente2.setImagenFondo(new di.dam.ejemploclase6componente3.ImagenFondo(new java.io.File("/home/jose/Escritorio/LogoInsti4.png"),0.5f));

        javax.swing.GroupLayout jPanelImagenTransparente2Layout = new javax.swing.GroupLayout(jPanelImagenTransparente2);
        jPanelImagenTransparente2.setLayout(jPanelImagenTransparente2Layout);
        jPanelImagenTransparente2Layout.setHorizontalGroup(
            jPanelImagenTransparente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImagenTransparente2Layout.setVerticalGroup(
            jPanelImagenTransparente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDividendo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDivisor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModificar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelImagenTransparente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(837, 837, 837)
                                .addComponent(ComponenteError, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelResultado)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDividendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModificar)
                .addGap(18, 18, 18)
                .addComponent(jLabelResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComponenteError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelImagenTransparente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        try {
            Double result = Double.parseDouble(this.jTextFieldDividendo.getText()) / Double.parseDouble(this.jTextFieldDivisor.getText());
            jLabelResultado.setText("Resultado: " + result.toString());
            if (result.toString().equals("Infinity"))
                this.ComponenteError.setLblTexto("INFO: Dividir por cero es mala idea");
            else
                this.ComponenteError.setLblTexto("");
        }
        catch (Exception e){
            this.ComponenteError.setLblTexto("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private di.dam.ejemplo6componente.JPanelComponente ComponenteError;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelResultado;
    private di.dam.ejemploclase6componente3.JPanelImagenTransparente jPanelImagenTransparente2;
    private javax.swing.JTextField jTextFieldDividendo;
    private javax.swing.JTextField jTextFieldDivisor;
    // End of variables declaration//GEN-END:variables
}
