/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package di.dam.ejemploclase8.vista;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignBand;
import net.sf.jasperreports.engine.design.JRDesignExpression;
import net.sf.jasperreports.engine.design.JRDesignField;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JRDesignSection;
import net.sf.jasperreports.engine.design.JRDesignStaticText;
import net.sf.jasperreports.engine.design.JRDesignTextField;
import net.sf.jasperreports.engine.design.JasperDesign;

/**
 *
 * @author jose
 */
public class InformesJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InformesJFrame.class.getName());

    /**
     * Creates new form InformesJFrame
     */
    public InformesJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonGenerarJava = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonGenerarTabla = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonGenerarGrafico = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informes de DI");
        setLocationByPlatform(true);

        jLabel1.setText("Informe generado con Java");

        jButtonGenerarJava.setText("Generar");
        jButtonGenerarJava.addActionListener(this::jButtonGenerarJavaActionPerformed);

        jLabel2.setText("Informe con Tabla de datos");

        jButtonGenerarTabla.setText("Generar");
        jButtonGenerarTabla.addActionListener(this::jButtonGenerarTablaActionPerformed);

        jLabel3.setText("Informe con Gráfico de datos");

        jButtonGenerarGrafico.setText("Generar");
        jButtonGenerarGrafico.addActionListener(this::jButtonGenerarGraficoActionPerformed);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGenerarGrafico)
                    .addComponent(jButtonGenerarTabla)
                    .addComponent(jButtonGenerarJava))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonGenerarJava))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerarTabla)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGenerarGrafico)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonGenerarJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarJavaActionPerformed
        try {
            // Generamos el diseño del informe a imprimir
            JasperDesign jd = new JasperDesign();
            
            // Iniciamos el diseño
            jd.setName("Informe creado en Java con Sakila");    // Nombre
            jd.setPageWidth(595);                               // Ancho A4
            jd.setPageHeight(842);                              // Alto A4
            jd.setLeftMargin(20);                               // Márgenes
            jd.setRightMargin(20);
            jd.setTopMargin(20);
            jd.setBottomMargin(20);
            
            // Iniciamos la Query del informe
            String sql = "SELECT title, release_year, length, rating FROM film;";   // SQL
            JRDesignQuery query = new JRDesignQuery();                              // Consulta para el informe
            query.setText(sql);
            jd.setQuery(query);                                                     // Asignamos la query al diseño
            
            // Creamos los campos del informe
            JRDesignField fieldTitle = new JRDesignField();
            fieldTitle.setName("title");                          // Nombre del campo
            fieldTitle.setValueClass(String.class);                // Tipo del campo (cadena)
            jd.addField(fieldTitle);                               // Añadimos el campo al diseño
            
            JRDesignField fieldYear = new JRDesignField();
            fieldYear.setName("release_year");                      // Nombre del campo
            fieldYear.setValueClass(java.sql.Date.class);           // Tipo del campo (Fecha)
            jd.addField(fieldYear);                                 // Añadimos el campo al diseño
            
            JRDesignField fieldLength = new JRDesignField();
            fieldLength.setName("length");                          // Nombre del campo
            fieldLength.setValueClass(Integer.class);               // Tipo del campo (entero)
            jd.addField(fieldLength);                               // Añadimos el campo al diseño
            
            JRDesignField fieldRating = new JRDesignField();
            fieldRating.setName("rating");                          // Nombre del campo
            fieldRating.setValueClass(String.class);                // Tipo del campo (cadena)
            jd.addField(fieldRating);                               // Añadimos el campo al diseño
            
            // Añadimos la banda de detalle al informe
            JRDesignBand detailBand = new JRDesignBand();           // Añadimos la banda de detalle
            detailBand.setHeight(20);                               // Le damos la altura
            
            JRDesignTextField tTitle = new JRDesignTextField();    // Campos de la cabecera
            tTitle.setBlankWhenNull(true);                         // Si viene nulo que deje en blanco
            tTitle.setX(0);                                        // Coordenadas en su banda
            tTitle.setY(0);
            tTitle.setWidth(200);                                  // Tamaño
            tTitle.setHeight(20);
            tTitle.setExpression(new JRDesignExpression("$F{title}"));
            detailBand.addElement(tTitle);                         // Añadimos el elemento a la banda
            
            JRDesignTextField tYear = new JRDesignTextField();    // Campos de la cabecera
            tYear.setBlankWhenNull(true);                         // Si viene nulo que deje en blanco
            tYear.setX(210);                                      // Coordenadas en su banda
            tYear.setY(0);
            tYear.setWidth(50);                                   // Tamaño
            tYear.setHeight(20);
            tYear.setExpression(new JRDesignExpression("$F{release_year}"));
            detailBand.addElement(tYear);                         // Añadimos el elemento a la banda
            
            JRDesignTextField tRating = new JRDesignTextField();    // Campos de la cabecera
            tRating.setBlankWhenNull(true);                         // Si viene nulo que deje en blanco
            tRating.setX(280);                                      // Coordenadas en su banda
            tRating.setY(0);
            tRating.setWidth(100);                                   // Tamaño
            tRating.setHeight(20);
            tRating.setExpression(new JRDesignExpression("$F{rating}"));
            detailBand.addElement(tRating);                         // Añadimos el elemento a la banda            
            
            JRDesignTextField tLength = new JRDesignTextField();    // Campos de la cabecera
            tLength.setBlankWhenNull(true);                         // Si viene nulo que deje en blanco
            tLength.setX(390);                                      // Coordenadas en su banda
            tLength.setY(0);
            tLength.setWidth(100);                                   // Tamaño
            tLength.setHeight(20);
            tLength.setExpression(new JRDesignExpression("$F{length}"));
            detailBand.addElement(tLength);                         // Añadimos el elemento a la banda   
            
            ((JRDesignSection)jd.getDetailSection()).addBand(detailBand);   // Añadimos la banda al diseño
            
            // Añadimos la cabecera
            JRDesignBand headerBand = new JRDesignBand();                   // Creamos la cabecera
            headerBand.setHeight(30);                                       // Le damos un ancho
            
            JRDesignStaticText stTitle = new JRDesignStaticText();         // Empezamos con los títulos de la cabecera
            stTitle.setText("Título");                                     // Definimos la columna igual que el detalle
            stTitle.setX(0);
            stTitle.setY(0);
            stTitle.setWidth(200);
            stTitle.setHeight(30);
            stTitle.setBold(true); // Negrita
            stTitle.setForecolor(Color.orange); // Naranja
            headerBand.addElement(stTitle);                               // Lo añadimos a la banda de cabecera
            
            JRDesignStaticText stYear = new JRDesignStaticText();         // Empezamos con los títulos de la cabecera
            stYear.setText("Año");                                      // Definimos la columna igual que el detalle
            stYear.setX(210);
            stYear.setY(0);
            stYear.setWidth(50);
            stYear.setHeight(30);
            stYear.setBold(true); // Negrita
            stYear.setForecolor(Color.orange); // Naranja
            headerBand.addElement(stYear);                                // Lo añadimos a la banda de cabecera
            
            JRDesignStaticText stRating = new JRDesignStaticText();         // Empezamos con los títulos de la cabecera
            stRating.setText("Valoración");                                     // Definimos la columna igual que el detalle
            stRating.setX(280);
            stRating.setY(0);
            stRating.setWidth(100);
            stRating.setHeight(30);
            stRating.setBold(true); // Negrita
            stRating.setForecolor(Color.orange); // Naranja
            headerBand.addElement(stRating);                                // Lo añadimos a la banda de cabecera
            
            JRDesignStaticText stLength = new JRDesignStaticText();         // Empezamos con los títulos de la cabecera
            stLength.setText("Duración");                                     // Definimos la columna igual que el detalle
            stLength.setX(390);
            stLength.setY(0);
            stLength.setWidth(100);
            stLength.setHeight(30);
            stLength.setBold(true); // Negrita
            stLength.setForecolor(Color.orange); // Naranja
            headerBand.addElement(stLength);                                // Lo añadimos a la banda de cabecera
            
            jd.setColumnHeader(headerBand);                                 // Añadimos la cabecera al diseño
            
            // Vamos a compilar el diseño
            JasperReport informe = JasperCompileManager.compileReport(jd);  // Creamos el informe con el compilador
            
            // Creamos la conexión de datos
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","di_user","Alandalus2526");
            
            // Generamos la impresora (no pasamos parámetros al no tener)
            JasperPrint impresora = JasperFillManager.fillReport(informe, new HashMap<>(), conn);
             
            // Abrimos el dialogo de guardar para obligarlo a ser pdf
            if (impresora != null){
                // Creamos el diálogo
                JFileChooser jfc = new JFileChooser();
                // Le ponemos título
                jfc.setDialogTitle("Guardar Reporte como...");
                // Guardamos en el home de Linux y mi usuario, esto es a cambiar
                jfc.setSelectedFile(new File("/home/jose/Escritorio/Peliculas.pdf"));
                // Filtramos para ver solo pdfs
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF","pdf");
                jfc.setFileFilter(filtro);
                // Mostramos el diálogo 
                int opcionSeleccionada = jfc.showSaveDialog(this); // TODO Ojo con cancelar
                // Si le damos a guardar:
                if (opcionSeleccionada == JFileChooser.APPROVE_OPTION) {
                    // Preparamos fichero y ruta
                    File archivoAguardar = jfc.getSelectedFile();                    
                    String path = jfc.getSelectedFile().getAbsolutePath();
                    if (!path.toLowerCase().endsWith(".pdf")) {
                        archivoAguardar = new File(path + ".pdf");
                    }                    
                    // Guardamos el fichero
                    JasperExportManager.exportReportToPdfFile(impresora, archivoAguardar.getAbsolutePath());
                    System.out.println("PDF guardado en: " + archivoAguardar.getAbsolutePath());
                    
                    // Abrimos el fichero
                    if (Desktop.isDesktopSupported()) {
                        Desktop desktop = Desktop.getDesktop();
                        if (archivoAguardar.exists()) {
                            // AL final mostramos el fichero
                            desktop.open(archivoAguardar);
                        }
                    }
                }
            }     
        } catch (SQLException | JRException | IOException ex) {
            System.getLogger(InformesJFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(this, "Error al generar el PDF: " + ex.getMessage());
        }           
    }//GEN-LAST:event_jButtonGenerarJavaActionPerformed

    private void jButtonGenerarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarTablaActionPerformed
        JOptionPane.showMessageDialog(this, "Esta opción aún no está implementada");
    }//GEN-LAST:event_jButtonGenerarTablaActionPerformed

    private void jButtonGenerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarGraficoActionPerformed
        JOptionPane.showMessageDialog(null, "Esta opción aún no está implementada");
    }//GEN-LAST:event_jButtonGenerarGraficoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarGrafico;
    private javax.swing.JButton jButtonGenerarJava;
    private javax.swing.JButton jButtonGenerarTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
